
name: build

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  MKN_KUL_GIT_CO: --depth 1
  CURL_GET: curl -fL --retry 3 --retry-delay 2
  PATH_GET: https://github.com/mkn/mkn/releases/download/latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        $CURL_GET -o mkn ${PATH_GET}/mkn_nix && chmod +x mkn
        KLOG=2 ./mkn clean build run -dtOa "-std=c++20 -fPIC"
        KLOG=2 ./mkn build run -dtOa "-std=c++20 -fPIC" -p test

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        $CURL_GET -o mkn ${PATH_GET}/mkn_arm_osx && chmod +x mkn
        KLOG=2 ./mkn clean build run -dtOa "-std=c++20 -fPIC"
        KLOG=2 ./mkn build run -tOa "-std=c++20 -fPIC" -p test

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12.5'
    - shell: cmd
      env:
        MKN_CL_PREFERRED: 1
        KLOG: 5
        PYTHON: python
      run: | # /bin/link interferes with cl/link.exe
        bash -c "rm /bin/link"
        bash -c "python3 -m pip install conan -U && python3 -m conans.conan profile detect"
        copy res\win\conanfile.txt conanfile.txt
        %CURL_GET% -o mkn.exe %PATH_GET%/mkn.exe
        bash -c './mkn -v'
        bash -c './mkn clean build run -dtOa "-EHsc -std:c++20"'
        bash -c './mkn build run -tOa "-EHsc -std:c++20" -p test'
